---
# environment Name
oah_env_name: oah-bes-vm
#GUI Flag
oah_vm_gui: false
# `vagrant_box` .
#vagrant_box: OAH/ubuntu1404
vagrant_box: "hashicorp/bionic64"
vagrant_user: vagrant
oah_env_user: vagrant
oah_user: oahdev


# If you need to run multiple instances of Openhack VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_cluster_vm_names: ['oah-bes-cluster-vm1','oah-bes-cluster-vm2','oah-bes-cluster-vm3']
vagrant_hostname: oah-bes-vm.dev
vagrant_machine_name: oah-bes-vm
#vagrant_ip: 192.168.88.88
vagrant_ip: 0.0.0.0

vagrant_public_ip: ""

vagrant_synced_folders: []
vagrant_memory: 1024
vagrant_cpus: 1 

oahvm_cron_jobs: []
  